### ISSUE TITLE
bigwig data preparation section shows a couple of erroneous commands (maybe)

### ISSUE THREAD

**Issue by sergpolly** [higlass/higlass-docs#11]
It looks like the `chromsizes` and  `bigiwg` ingestion commands, as presented in the TLDR section of "Data Preparation" part of docs:
https://github.com/higlass/higlass-docs/blob/master/data_preparation.rst#bigwig-files
have some rather misleading errors ...

now:
[screenshot]
![screenshot from 2018-12-21 09-35-33](https://user-images.githubusercontent.com/6790270/50347610-1dd4bc80-0504-11e9-9ec6-3f1360857a92.png)

[text]
```bash
ingest_tileset --filetype chromsizes-tsv --datatype chromsizes --coordSystem hg19 chromSizes.tsv
ingest_tileset --filetype bigwig --datatype vector --coordSystem hg19 chromSizes.tsv
```

should be:
```bash
ingest_tileset --filetype chromsizes-tsv --datatype chromsizes --coordSystem hg19 --filename chromSizes.tsv
ingest_tileset --filetype bigwig --datatype vector --coordSystem hg19 --filename cnvs_hw.bigWig
```

because `ingest_tileset` does not accept any arguments, only named options - so input files should be specified with `--filename` option.
Also ` --filetype bigwig` in combination with `chromSizes.tsv` is clearly an error.

**Comment by pkerpedjiev** [comment]
Thanks for pointing this out! 

I just submitted a PR with your suggestions: https://github.com/higlass/higlass/pull/497

Just FYI: the docs now live in the higlass repo: https://github.com/higlass/higlass/tree/develop/docs

Feel free to directly propose such changes as a PR in the future. All the docs are in the *.rst files in the directory above.

**Comment by sergpolly** [comment]
Thank you!
I also just wasn't sure what does `chromsizes` ingestion implies - as it always seemed to me that HiGlass is aware of the `coordSystem` , somehow/somewhere internally - at least for other data-types

**Comment by pkerpedjiev** [comment]
Previously, we used a default semantic ordering (chr1, chr2, ... chrX, chrY, chrM) for all bigWig files. In the latest version we enforce associating bigWigs with a chromsizes file so that we know the order in which to display chromosomes.
